apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: postgres_deployment
spec:
  replicas: 2
  selectors:
    matchLabels:
      labels: 
        component: postgres
    spec:
      volumes:
      - name: postgres-storage 
        PersistentVolumeClaim:
          claimName: Database-persistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: var/lib/postgres/data
              subPath: postgres 
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretsKeyRef:
                  name: pgpassword 
                  key: PGPASSWORD 